// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/counter.tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/AddTodo.tsx";
import * as $$1 from "./islands/App.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/Todo.tsx";
import * as $$4 from "./islands/TodoCount.tsx";
import * as $$5 from "./islands/TodoList.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/counter.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/AddTodo.tsx": $$0,
    "./islands/App.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/Todo.tsx": $$3,
    "./islands/TodoCount.tsx": $$4,
    "./islands/TodoList.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
